-- MySQL Script generated by MySQL Workbench
-- 03/13/16 22:58:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agifsc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agifsc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agifsc` DEFAULT CHARACTER SET utf8 ;
USE `agifsc` ;

-- -----------------------------------------------------
-- Table `agifsc`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`TipoUsuario` (
  `idtipo` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`Usuario` (
  `cpf` VARCHAR(14) NOT NULL,
  `idtipo` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `idtipo`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`idtipo` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`idtipo`)
    REFERENCES `agifsc`.`TipoUsuario` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`TipoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`TipoEvento` (
  `idevento` INT NOT NULL,
  `descricao` VARCHAR(10) NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`aluno` (
  `cpf` VARCHAR(14) NOT NULL,
  `matricula` VARCHAR(10) NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_aluno_Usuario1`
    FOREIGN KEY (`cpf`)
    REFERENCES `agifsc`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`turma` (
  `idturma` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`matricula` (
  `idturma` INT NOT NULL,
  `cpf` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idturma`, `cpf`),
  INDEX `fk_matricual_aluno1_idx` (`cpf` ASC),
  CONSTRAINT `fk_matricual_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `agifsc`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricual_aluno1`
    FOREIGN KEY (`cpf`)
    REFERENCES `agifsc`.`aluno` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agifsc`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agifsc`.`calendario` (
  `idcalendario` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `idevento` INT NOT NULL,
  `datainicio` DATETIME NULL,
  `datafim` DATETIME NULL,
  PRIMARY KEY (`idcalendario`, `idevento`, `cpf`),
  INDEX `fk_calendario_TipoEvento1_idx` (`idevento` ASC),
  INDEX `fk_calendario_Usuario1_idx` (`cpf` ASC),
  CONSTRAINT `fk_calendario_TipoEvento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `agifsc`.`TipoEvento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_Usuario1`
    FOREIGN KEY (`cpf`)
    REFERENCES `agifsc`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
